# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: MainnetZ DragonZ Indexer
description: Indexer for DragonZ Series 1 contract
networks:
  - id: 2016 # MainnetZ Mainnet
    rpc_config:
      url: https://mainnet-rpc.mainnetz.io
    start_block: 1
    contracts:
      - name: erc721
        address: "0x8222aa611aEe3EA1d3b2Fd6a0a4f3805bd175a48" #DragonZ Series 1
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
# Unordered multichain mode allows you to index events from multiple chains
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
